// <auto-generated>
// ReSharper disable All

using IF.ThreadPilot.Core.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IF.ThreadPilot.Core.Infrastructure.Entities.Persistence.Data
{
    // customer
    public partial class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> builder)
        {
            builder.ToTable("customer", "public");
            builder.HasKey(x => x.SsNo).HasName("customer_pkey");

            builder.Property(x => x.SsNo).HasColumnName(@"SSNo").HasColumnType("character varying(13)").IsRequired().HasMaxLength(13).ValueGeneratedNever();
            builder.Property(x => x.Firstname).HasColumnName(@"firstname").HasColumnType("character varying(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Surname).HasColumnName(@"surname").HasColumnType("character varying(50)").IsRequired().HasMaxLength(50);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Customer> builder);
    }

}
// </auto-generated>
