// <auto-generated>
// ReSharper disable All

using IF.ThreadPilot.Core.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IF.ThreadPilot.Core.Infrastructure.Entities.Persistence.Data
{
    // insuranceType
    public partial class InsuranceTypeConfiguration : IEntityTypeConfiguration<InsuranceType>
    {
        public void Configure(EntityTypeBuilder<InsuranceType> builder)
        {
            builder.ToTable("insuranceType", "public");
            builder.HasKey(x => x.Id).HasName("insuranceType_pkey");

            builder.Property(x => x.Id).HasColumnName(@"id").HasColumnType("integer").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType("character varying(30)").IsRequired().HasMaxLength(30);
            builder.Property(x => x.Cost).HasColumnName(@"cost").HasColumnType("integer").IsRequired();

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<InsuranceType> builder);
    }

}
// </auto-generated>
