// <auto-generated>
// ReSharper disable All

using IF.ThreadPilot.Core.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace IF.ThreadPilot.Core.Infrastructure.Entities.Persistence.Data
{
    // vehicle
    public partial class VehicleConfiguration : IEntityTypeConfiguration<Vehicle>
    {
        public void Configure(EntityTypeBuilder<Vehicle> builder)
        {
            builder.ToTable("vehicle", "public");
            builder.HasKey(x => x.RegNo).HasName("vehicle_pkey");

            builder.Property(x => x.RegNo).HasColumnName(@"regNo").HasColumnType("character varying(6)").IsRequired().HasMaxLength(6).ValueGeneratedNever();
            builder.Property(x => x.Brand).HasColumnName(@"brand").HasColumnType("character varying(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Model).HasColumnName(@"model").HasColumnType("character varying(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Owner).HasColumnName(@"Owner").HasColumnType("character varying(13)").IsRequired().HasMaxLength(13);

            InitializePartial(builder);
        }

        partial void InitializePartial(EntityTypeBuilder<Vehicle> builder);
    }

}
// </auto-generated>
