// <auto-generated>
// ReSharper disable All

using IF.ThreadPilot.Core.Domain.Entities;
using Microsoft.EntityFrameworkCore.Design;

namespace IF.ThreadPilot.Core.Infrastructure.Entities.Persistence.Data
{
    public partial class ThreadPilotDbContextFactory : IDesignTimeDbContextFactory<ThreadPilotDbContext>
    {
        public ThreadPilotDbContext CreateDbContext(string[] args)
        {
            return new ThreadPilotDbContext();
        }
    }
}
// </auto-generated>
