// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace IF.ThreadPilot.Core.Domain.Entities
{
    // customer
    public class Customer
    {
        public string SsNo { get; set; } // SSNo (Primary key) (length: 13)
        public string Firstname { get; set; } // firstname (length: 50)
        public string Surname { get; set; } // surname (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child FactCustomerInsurances where [fact_customer_insurance].[SSNo] point to this entity (fk_fact_customer_insurance_ssno)
        /// </summary>
        public virtual ICollection<FactCustomerInsurance> FactCustomerInsurances { get; set; } // fact_customer_insurance.fk_fact_customer_insurance_ssno

        public Customer()
        {
            FactCustomerInsurances = new List<FactCustomerInsurance>();
        }
    }

}
// </auto-generated>
