// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace IF.ThreadPilot.Core.Domain.Entities
{
    // fact_customer_insurance
    public class FactCustomerInsurance
    {
        public string SsNo { get; set; } // SSNo (Primary key) (length: 13)
        public int InsuranceTypeId { get; set; } // insuranceTypeId (Primary key)
        public string Identity { get; set; } // identity (Primary key) (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [fact_customer_insurance].([SsNo]) (fk_fact_customer_insurance_ssno)
        /// </summary>
        public virtual Customer Customer { get; set; } // fk_fact_customer_insurance_ssno

        /// <summary>
        /// Parent InsuranceType pointed by [fact_customer_insurance].([InsuranceTypeId]) (fk_fact_customer_insurance_insuranceTypeId)
        /// </summary>
        public virtual InsuranceType InsuranceType { get; set; } // fk_fact_customer_insurance_insuranceTypeId
    }

}
// </auto-generated>
