// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace IF.ThreadPilot.Core.Domain.Entities
{
    // insuranceType
    public class InsuranceType
    {
        public int Id { get; set; } // id (Primary key)
        public string Name { get; set; } // name (length: 30)
        public int Cost { get; set; } // cost

        // Reverse navigation

        /// <summary>
        /// Child FactCustomerInsurances where [fact_customer_insurance].[insuranceTypeId] point to this entity (fk_fact_customer_insurance_insuranceTypeId)
        /// </summary>
        public virtual ICollection<FactCustomerInsurance> FactCustomerInsurances { get; set; } // fact_customer_insurance.fk_fact_customer_insurance_insuranceTypeId

        public InsuranceType()
        {
            FactCustomerInsurances = new List<FactCustomerInsurance>();
        }
    }

}
// </auto-generated>
