// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace IF.ThreadPilot.Core.Domain.Entities
{
    // vehicle
    public class Vehicle
    {
        public string RegNo { get; set; } // regNo (Primary key) (length: 6)
        public string Brand { get; set; } // brand (length: 50)
        public string Model { get; set; } // model (length: 50)
        public string Owner { get; set; } // Owner (length: 13)
    }

}
// </auto-generated>
